### ISSUE TITLE
Default directories/files ( .vim, .vimrc )

### ISSUE THREAD

**Issue by LehaMotovilov** [cheshir/vim-config#1]
Sorry dude, but I don't have default directories such as .vim and file .vimrc

Can you add additional check for you installation FAQ.

**Comment by LehaMotovilov** [comment]
Also check this: https://gist.github.com/LehaMotovilov/1e74c77edd9f0d5f6ece506746500976

**Comment by cheshir** [comment]
@LehaMotovilov, thank you for your feedback. [Check this out](https://github.com/cheshir/vim-config/commit/234b0caddfd6406d8b0f5aec8fda6d14d48b3bd8).
